spring:
  profiles:
    include: local-db,aws,oauth2

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      format_sql: true
      default_batch_fetch_size: 500
      use_sql_comments: true
    open-in-view: true
    session:
      store-type: jdbc
  session:
    jdbc:
      initialize-schema: always

  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG